# Generated by Django 5.0.3 on 2024-03-17 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, choices=[('client', 'client'), ('admin', 'admin')], max_length=25)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=150)),
                ('user_id', models.IntegerField(default=0)),
                ('ip_client', models.CharField(blank=True, max_length=40)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
