# Generated by Django 5.0.3 on 2024-03-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_codes', '0003_chatmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
